openapi: 3.0.0
info:
  title: web-template-back
  version: 1.0.0
  description: web-template-back
servers:
  - url: !Sub "https://${StageMap.${Stage}.frontDomain}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"

paths:
  /test:
    get:
      summary: Test function
      description: Test function
      operationId: testGet
      parameters:
        - name: n
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                type: string
        "default":
          description: "Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TestFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
  components:
    schemas:
      Error:
        type: object
        properties:
          status:
            type: integer
          message:
            type: string
        required:
          - status
          - message
      # Enum
      Stage:
        type: string
        enum:
          - dev
          - prod
