openapi: "3.0.3"
info:
  title: web-template-back
  version: 1.0.0
  description: web-template-back

paths:
  /api/test:
    get:
      summary: Test function
      description: Test function
      operationId: testGet
      parameters:
        - name: n
          in: query
          required: false
          schema:
            type: number
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "default":
          description: "Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: Post
        responses:
          "200":
            statusCode: "200"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TestFunction.Arn}/invocations"

components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
      required:
        - status
        - message
    # Enum
    Stage:
      type: string
      enum:
        - local
        - dev
        - prod
