version = 1.0

[default.local_start_api.parameters]
port = 3001
warm_containers = "EAGER"
skip_pull_image = true
parameter_overrides = "Stage=local"

[dev.deploy.parameters]
debug = true
stack_name = "web-template-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pc9rxjxha1vt"
s3_prefix = "deploy/web-template/dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = ["Stage=dev"]

[prod.deploy.parameters]
stack_name = "web-template-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pc9rxjxha1vt"
s3_prefix = "web-template/prod"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = ["Stage=prod"]