AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: web-template-back

Parameters:
  Stage:
    Type: String
    AllowValues: [local, dev, prod]
    Default: local

Mappings:
  StageMap:
    local:
      frontDomain: web-template-back-local
    dev:
      frontDomain: web-template-back-dev
    prod:
      frontDomain: web-template-back-prod

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: nodejs20.x
    Architecture: arm64
    Environment:
      Variables:
        STAGE: !Ref Stage

Resources:
  # S3
  WebTemplateFrontBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "tota-web-template-front-${Stage}"
      Tags:
        id: "web-template-front"
        Stage: !Ref Stage

  # API Gateway
  WebTemplateBackApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "web-template-back-${Stage}"
      StageName: !Ref Stage
      EndpointConfiguration: REGIONAL
      Tags:
        id: "web-template-back"
        Stage: !Ref Stage
      DefinitionBody:
        Fn::TransForm:
          Name: "AWS::Include"
          Parameters:
            Location: "../openapi.yml"
      Cors:
        AllowOrigin: !Join ["", ["'", "*", "'"]]
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"

  # Lambda
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/test
      Handler: get.handler
      Timeout: 3
      Events:
        WebTemplateBackApi:
          Type: Api
          Properties:
            path: /test
            method: get
            RestApiId: !Ref WebTemplateBackApi
